name: Certbot Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: multiarch/ubuntu-core:arm64-22.04
      options: --privileged

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-venv libaugeas0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Set up Certbot
        run: |
          sudo python3 -m venv /opt/certbot/
          sudo /opt/certbot/bin/pip install --upgrade pip
          sudo /opt/certbot/bin/pip install certbot
      - name: Upload Certbot to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: certbot-artifact
          path: /opt/certbot/
