name: Build Certbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_aarch64:
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest aarch64
    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update -y
            apt-get install -y software-properties-common
            add-apt-repository ppa:deadsnakes/ppa
            apt-get install -y python3.11 python3.11-pip python3.11-venv libaugeas0
            update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1
          run: |
            python3 -m venv /opt/certbot/
            /opt/certbot/bin/pip install --upgrade pip
            /opt/certbot/bin/pip install certbot
            tar -czf certbot-artifact.tar.gz -C /opt certbot
            cp certbot-artifact.tar.gz "/artifacts/certbot-artifact.tar.gz"
            echo "Produced artifact at /artifacts/certbot-artifact.tar.gz"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: certbot-artifact
          path: /artifacts/certbot-artifact.tar.gz
