name: Build Certbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64, arm64]

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-venv libaugeas0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Create Certbot
      run: |
        python -m venv /opt/certbot/
        /opt/certbot/bin/pip install --upgrade pip
        /opt/certbot/bin/pip install certbot
    - name: Archive /opt/certbot
      run: |
        tar -czf certbot-artifact-${{ runner.arch }}.tar.gz -C /opt certbot
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: certbot-artifact-${{ runner.arch }}
        path: certbot-artifact-${{ runner.arch }}.tar.gz
