name: Build Certbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_aarch64:
    runs-on: ubuntu-latest
    name: Build on ubuntu-devel aarch64
    steps:
      - uses: uraimo/run-on-arch-action@v2.6.0
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_devel
          githubToken: ${{ github.token }}
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          # Pass artifact_name environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          # Install certbot dependency
          install: |
            apt-get update -y
            apt-get install -y software-properties-common
            add-apt-repository universe
            apt-get install -y python3 python3-pip python3-venv libaugeas0
          # Build certbot
          run: |
            python3 -m venv /opt/certbot/
            /opt/certbot/bin/pip install --upgrade pip
            LDFLAGS='--unresolved-symbols=ignore-all -lpython3.11' /opt/certbot/bin/pip install certbot
            tar -czf certbot-artifact.tar.gz -C /opt certbot
            cp certbot-artifact.tar.gz "/artifacts/certbot-artifact.tar.gz"
            echo "Produced artifact at /artifacts/certbot-artifact.tar.gz"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: certbot-artifact
          path: ./artifacts/certbot-artifact.tar.gz
