name: Install and Build Certbot
on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-venv libaugeas0

    - name: Create Certbot venv
      run: |
        sudo python3 -m venv /opt/certbot/
        sudo /opt/certbot/bin/pip install --upgrade pip
        sudo /opt/certbot/bin/pip install certbot

    - name: Archive /opt/certbot
      run: |
        tar -czf certbot-artifact.tar.gz -C /opt certbot

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: certbot-artifact
        path: certbot-artifact.tar.gz
